# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'AnalysysSwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 
  pod 'AnalysysAgent', :path => '../'
  
  pod 'Bugly'
  pod 'UMengAnalytics-NO-IDFA','4.2.5'
  pod 'IQKeyboardManager'
  pod 'MBProgressHUD'

end

